stages:
  #- test
  - debug_build
  - release_build
  - deploy

.build-android:
  image: cirrusci/flutter:stable
  tags: [ docker ]
  variables:
    BUILD_TYPE: none
  script:
    - echo Build ${BUILD_TYPE} app
    - flutter build appbundle --${BUILD_TYPE}
  artifacts:
    paths:
      - build/app/outputs/bundle/$BUILD_TYPE/app-${BUILD_TYPE}.aab

.build-mac-os:
  tags: [ mac-os ]
  variables:
    BUILD_TYPE: none
  script:
    - echo Build ${BUILD_TYPE} app
    - flutter build macos --${BUILD_TYPE}
    - cd installers/dmg_creation
    - appdmg ${BUILD_TYPE}_config.json ./${BUILD_TYPE}_synopce.dmg
  artifacts:
    paths:
      - installers/dmg_creation/${BUILD_TYPE}_synopce.dmg

#flutter_test:
#  extends:
#    - .with-flutter
#  image: cirrusci/flutter:stable
#  stage: test
#  tags: [ docker ]
#  script:
#    - flutter test

debug_build_android:
  extends:
    - .build-android
  stage: debug_build
  variables:
    BUILD_TYPE: debug
  before_script:
    - sh ./scripts/with_flutter.sh
  except:
    - tags

debug_build_macos:
  extends:
    - .build-mac-os
  stage: debug_build
  variables:
    BUILD_TYPE: debug
  before_script:
    - sh ./scripts/with_flutter.sh
  except:
    - tags

release_build_android:
  extends:
    - .build-android
  stage: release_build
  variables:
    BUILD_TYPE: release
  before_script:
    - sh ./scripts/setup_app_version.sh
    - sh ./scripts/setup_android_sign.sh
    - sh ./scripts/with_flutter.sh
  only:
    - tags

release_build_macos:
  extends:
    - .build-mac-os
  stage: release_build
  variables:
    BUILD_TYPE: release
  before_script:
    - sh ./scripts/setup_app_version.sh
    - sh ./scripts/with_flutter.sh
  only:
    - tags

deploy:
  image: node:16-alpine
  tags: [ docker ]
  stage: deploy
  dependencies:
    - release_build_android
    - release_build_macos
  before_script:
    - npm install --location=global appcenter-cli
    - appcenter login --token $APPCENTER_API_TOKEN
  script:
    - appcenter distribute release -f build/app/outputs/bundle/release/app-release.aab -g Collaborators --app Synopce/Synopce-android
    - appcenter distribute release -f installers/dmg_creation/release_synopce.dmg -g Collaborators --app Synopce/Synopce-mac-os
  only:
    - tags