stages:
  - test
  - build

flutter_test:
  image: cirrusci/flutter:stable
  stage: test
  tags: [docker]
  script:
    - flutter test

flutter_build_android:
  image: cirrusci/flutter:stable
  stage: build
  tags: [docker]
  before_script:
    - flutter packages get
    - flutter clean
  script:
     - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk

flutter_build_macos:
  stage: build
  tags: [mac-os]
  before_script:
    - flutter packages get
    - flutter clean
  script:
     - flutter build macos
     - cd installers/dmg_creation
     - appdmg config.json ./dsm_app.dmg
  artifacts:
    paths:
      - installers/dmg_creation/dsm_app.dmg