stages:          # List of stages for jobs, and their order of execution
  - test
  - build

flutter_test: # Name of the lane
  stage: test # type of stage
  script:
    - flutter test # Run Flutter test

flutter_build_android: #Job name
  stage: build # kind of job
  before_script:
    - flutter packages get
    - flutter clean
  script:
     - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk