name: synopce
description: Client application for access to Synology Disk and note station
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  synoapi:
#    path: ../synoapi
    git:
      url: https://github.com/chitkiu/synoapi.git
      ref: master

  cupertino_icons: ^1.0.5
  file_picker: ^5.2.5
  flutter_secure_storage: ^7.0.1
  responsive_builder: ^0.5.0+1
  flutter_fancy_tree_view: ^0.5.3+2
  flutter_platform_widgets: ^2.2.6
  logging: ^1.1.1
  rxdart: ^0.27.7
  get: ^4.6.5
  flutter_html: ^2.2.1
  zoom_widget: ^2.0.0
  sentry_flutter: ^6.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true