default_platform(:android)
platform :android do
  lane :deploy_to_playstore do
    upload_to_play_store(
          aab: '../build/app/outputs/bundle/release/app-release.aab',
          skip_upload_metadata: true,
          skip_upload_images: true,
          skip_upload_screenshots: true,
          track: 'internal',
    )
  end
end