default_platform(:android)
platform :android do
  desc "Build a Flutter apk"
  lane :build do
    Dir.chdir("../..") do
      sh "flutter packages get"
      sh "flutter clean"
      sh "flutter build apk"
    end
  end
end